config/routes.rb
Rails.application.routes.draw do
  resources :favourites do
  	collection do
  		get 'search'
  		get 'compare'
  	end
  end

  get '/', to: 'favourites#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favourite.rb
class Favourite < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  before_action :set_favourite, only: [:show, :edit, :update, :destroy]

  # GET /favourites
  # GET /favourites.json
  def index
    @favourites = Favourite.all
  end

  # GET /favourites/1
  # GET /favourites/1.json
  def show
  end

  # GET /favourites/new
  def new
    @favourite = Favourite.new
  end

  # GET /favourites/1/edit
  def edit
  end

  # GET /favourites/search
  def search
    @query = params[:query]
    return unless @query.present?

    require 'net/http'
    uri = URI.parse('https://api.spotify.com/v1/search?' + {q: @query, type: 'track'}.to_query)
    json = Net::HTTP.get(uri)

    # This lets me dump out a binary value nicely
    #render json: json

    # Capture results as a hash
    result_set = JSON.parse(json)
    @results = result_set["tracks"]["items"]
  end

  def compare
    @first_person = params[:first_person]
    @second_person = params[:second_person]

    return unless (@first_person.present? and @second_person.present?)

    @all_favourites = Favourite.where(person: [@first_person, @second_person]).order(:spotify_id)
    @intersection = []

    @intersection_objects = @all_favourites.select("spotify_id, person").find_all { |f| @all_favourites.find{ |f2| f2.spotify_id == f.spotify_id && f2.person != f.person} }
    if !@intersection_objects.nil?
      @intersection_objects.each_entry{ |f| @intersection |= [f.spotify_id]  }
    end

  end

  # POST /favourites
  # POST /favourites.json
  def create
    @favourite = Favourite.new(favourite_params)

    respond_to do |format|
      if @favourite.save
        format.html { redirect_to @favourite, notice: 'Favourite was successfully created.' }
        format.json { render :show, status: :created, location: @favourite }
      else
        format.html { render :new }
        format.json { render json: @favourite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /favourites/1
  # PATCH/PUT /favourites/1.json
  def update
    respond_to do |format|
      if @favourite.update(favourite_params)
        format.html { redirect_to @favourite, notice: 'Favourite was successfully updated.' }
        format.json { render :show, status: :ok, location: @favourite }
      else
        format.html { render :edit }
        format.json { render json: @favourite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favourites/1
  # DELETE /favourites/1.json
  def destroy
    @favourite.destroy
    respond_to do |format|
      format.html { redirect_to favourites_url, notice: 'Favourite was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favourite
      @favourite = Favourite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def favourite_params
      params.require(:favourite).permit(:person, :spotify_id, :name, :preview_url)
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def search
  	@query = params[:query]
  	return unless @query.present?

  	require 'net/http'
  	uri = URI.parse('https://api.spotify.com/v1/search?' + {q: @query, type: 'track'}.to_query)
  	json = Net::HTTP.get(uri)

  	# This lets me dump out a binary value
  	#render json: json

  	# Capture results as a hash
  	result_set = JSON.parse(json)
  	@results = result_set["tracks"]["items"]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/favourites/_form.html.erb
<%= form_with(model: favourite, local: true) do |form| %>
  <% if favourite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(favourite.errors.count, "error") %> prohibited this favourite from being saved:</h2>

      <ul>
      <% favourite.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :person %>
    <%= form.text_field :person, id: :favourite_person %>
  </div>

  <div class="field">
    <%= form.label :spotify_id %>
    <%= form.text_field :spotify_id, id: :favourite_spotify_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :favourite_name %>
  </div>

  <div class="field">
    <%= form.label :preview_url %>
    <%= form.text_field :preview_url, id: :favourite_preview_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/favourites/compare.html.erb
<h1>Compare Favourites</h1>

<%= form_tag(compare_favourites_path, method: :get, class: 'form-horizontal') do %>
	<div class="form-group">
		<%= label_tag(:first_person, "First Person:", class: 'col-md-2 control-label') %>
		<div class="col-md-8">
			<%= text_field_tag(:first_person, params[:first_person], class: 'form-control') %>
		</div>
	</div>
	<div class="form-group">
		<%= label_tag(:second_person, "Second Person:", class: 'col-md-2 control-label') %>
		<div class="col-md-8">
			<%= text_field_tag(:second_person, params[:second_person], class: 'form-control') %>
		</div>
		<div class="col-md-2">
			<%= submit_tag("Compare", class: 'btn btn-default') %>
		</div>
	</div>
<% end %>

<% if @all_favourites.present? %>

<div class="container-fluid">
	<div class="row">
		<% [@first_person, @second_person].each do |person|%>
		<div class="col-md-6">
			<h2><%= person %>'s Favourites
			<ul>
			<% @all_favourites.find_all{ |f| f.person == person }.each do |favourite| %>
				<% @is_shared = @intersection.any?{ |f| f == favourite.spotify_id} #%>
				<li class="<%= 'shared' if @is_shared %>">
					<% if @is_shared %>
						<span class="glyphicon glyphicon-star"></span>
					<% end %>
					<%= favourite.name %>
				</li>
			<% end %>
			</ul>
		</div>
		<% end %>
	</div>
</div>
<% end %>

app/views/favourites/edit.html.erb
<h1>Editing Favourite</h1>

<%= render 'form', favourite: @favourite %>

<%= link_to 'Show', @favourite %> |
<%= link_to 'Back', favourites_path %>

app/views/favourites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Favourites</h1>
<p><%= link_to 'Add your favourite songs', search_favourites_path %> into the system and then
  <%= link_to 'see who shares', compare_favourites_path %> your faves!</p>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Person</th>
      <th>Spotify</th>
      <th>Name</th>
      <th>Preview url</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @favourites.each do |favourite| %>
      <tr>
        <td><%= favourite.person %></td>
        <td><%= favourite.spotify_id %></td>
        <td><%= favourite.name %></td>
        <td>
          <% if favourite.preview_url.present? %>
            <a href=<%= favourite.preview_url %> target="_blank">Listen
              <span class="glyphicon glyphicon-play-circle"></span>
            </a>
          <% end %>
        </td>
        <td>
          <div class="btn-group">
          <%= link_to 'Show', favourite, class: 'btn btn-default' %>
          <%= link_to 'Edit', edit_favourite_path(favourite), class: 'btn btn-default' %>
          <%= link_to 'Destroy', favourite, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default' %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/favourites/new.html.erb
<h1>New Favourite</h1>

<%= render 'form', favourite: @favourite %>

<%= link_to 'Back', favourites_path %>

app/views/favourites/search.html.erb
<h1>Search for Favourite Songs</h1>

<%= form_tag(search_favourites_path, method: :get, class: 'form-horizontal') do %>
	<div class="form-group">
		<%= label_tag(:query, "Search for:", class: 'col-md-2 control-label') %>
		<div class="col-md-8">
		<%= text_field_tag(:query, params[:query], class: 'form-control') %>
		</div>
	</div>
	<div class="form-group">
		<%= label_tag(:person, "Your name:", class: 'col-md-2 control-label') %>
		<div class="col-md-8">
		<%= text_field_tag(:person, params[:person], class: 'form-control') %>
		</div>
		<div class="col-md-2">
			<%= submit_tag("Search", class: 'btn btn-default') %>
		</div>
	</div>
<% end %>

<% if @results.present? %>
	<h2>Songs Matching "<%=@query%>"</h2>

	<table class="table table-striped">
		<thead>
			<tr>
				<th>Name</th>
				<th>Artist(s)</th>
				<th>Album</th>
				<th>Preview</th>
			</tr>
		</thead>
		<tbody>
	<% @results.each do |track| %>
		<tr>
			<td>
				<span class="btn-group">
				<%= button_to favourites_path({
					favourite: {
						person: params[:person],
						spotify_id: track["id"],
						name: track["name"],
						preview_url: track["preview_url"]
					},
					method: :post}),
					{class: 'btn btn-primary btn-sm'} do %>
					<span class="glyphicon glyphicon-star-empty"></span>
				<% end %>
				</span>
				<%= track["name"] %>
			</td>
			<td><%= track["artists"].map{ |artist| artist["name"] }.join(", ") %></td>
			<td><%= track["album"]["name"]%></td>
			<td>
				<% if track["preview_url"].present? %>
				<a href=<%= "#{track['preview_url']}" %> target="_blank">Listen
					<span class="glyphicon glyphicon-play-circle"></span>
				</a>
				<% end %>
			</td>
		</tr>
	<% end %>
		</tbody>
	</table>
<% end %>

app/views/favourites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Person:</strong>
  <%= @favourite.person %>
</p>

<p>
  <strong>Spotify:</strong>
  <%= @favourite.spotify_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @favourite.name %>
</p>

<p>
  <strong>Preview url:</strong>
  <%= @favourite.preview_url %>
</p>

<%= link_to 'Edit', edit_favourite_path(@favourite) %> |
<%= link_to 'Back', favourites_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music</title>
    <%= csrf_meta_tags %>

	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<header>
	  	<nav class="navbar navbar-default">
	  		<div class="container-fluid">
	  			<a class="navbar-brand" href="/">
	  				<%= image_tag("music_notes.png", class: 'navbar-image') %>	
	  				Music Buddies
	  			</a>

	  			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	  				<ul class="nav navbar-nav">
	  					<li><%= link_to 'New Favourite', new_favourite_path %></li>
						<li><%= link_to 'Search for Favourites', search_favourites_path %></li>
						<li><%= link_to 'Compare Favourites', compare_favourites_path %></li>
	  				</ul>
	  			</div>

	  		</div>
	  	</nav>
  	</header>
    <%= yield %>
  </body>
</html>

app/views/songs/search.html.erb
<h1>Search for a Song</h1>

<%= form_tag(songs_search_path, method: :get) do %>
	<%= label_tag(:query, "Search for:") %>
	<%= text_field_tag(:query, @query) %>

	<%= submit_tag("Search") %>
<% end %>

<% if @results.present? %>
<h2>Song Matches</h2>
<p>You searched for "<em><%=@query%></em>".</p>
<ul>
	<% @results.each do |song| %>
	<li>
		<%= song["name"] %> (<%= song["artists"].map{ |artist| artist["name"] }.join(", ") %>)
	</li>
	<% end %>
</ul>
<% end %>